name: Continuous Deployment
on:
  push:
    branches: 
      - "main"

jobs:
  redeploying_everything:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Debug key format
        run: |
          ssh-keygen -lf ~/.ssh/id_rsa

      - name: Deploy
        run: |
          ssh -T ubuntu@ec2-3-238-142-128.compute-1.amazonaws.com << 'EOF'
            cd Excali-Paint
            git pull
            pnpm install
            pnpm run build
            pm2 restart ecosystem.config.js
          EOF
